[package]
name = "snarkos-profiler"
version = "1.3.16"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Profiler for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.colored]
version = "2"
optional = true

[features]
print-trace = [ "colored" ]
