[package]
name = "snarkos-consensus"
version = "1.3.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Consensus for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
version = "0.2.2"

[dependencies.snarkvm-curves]
version = "0.2.2"

[dependencies.snarkvm-dpc]
version = "0.2.2"

[dependencies.snarkvm-objects]
version = "0.2.2"

[dependencies.snarkvm-posw]
version = "0.2.2"

[dependencies.snarkvm-utilities]
version = "0.3.1"

[dependencies.snarkos-profiler]
path = "../profiler"
version = "1.3.3"

[dependencies.snarkos-storage]
path = "../storage"
version = "1.3.3"
default-features = false

[dependencies.anyhow]
version = "1.0.40"

[dependencies.chrono]
version = "0.4"
features = [ "serde" ]

[dependencies.hex]
version = "0.4.2"

[dependencies.parking_lot]
version = "0.11.1"

[dependencies.rand]
version = "0.8"

[dependencies.thiserror]
version = "1.0"

[dependencies.tracing]
default-features = false
features = [ "log" ]
version = "0.1"

[dev-dependencies.snarkos-testing]
path = "../testing"

[dev-dependencies.criterion]
version = "0.3"

[dev-dependencies.rand_xorshift]
version = "0.3"

[[bench]]
name = "transactions"
path = "benches/transactions.rs"
harness = false
